backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "img/uploads" # Media files will be stored in the repo under img/uploads

# source: https://www.netlifycms.org/docs/add-to-your-site/

